package com.mertokan.omnilogistics.core;

import com.mertokan.omnilogistics.OmniLogistics;
import com.mojang.blaze3d.platform.InputConstants;
import net.minecraft.client.gui.GuiGraphicsExtractor;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.inventory.AbstractContainerMenu;
import org.jetbrains.annotations.Nullable;

import java.util.function.IntSupplier;

/** Textured dark panel + light labels. Textures are generated by tools/gen_textures.py (256x256, or 512x512 when the panel is taller). */
public abstract class DarkScreen<M extends AbstractContainerMenu> extends AbstractContainerScreen<M> {
    public static final int TEXT = 0xFFE6EDF3;   // text needs its alpha since 1.21.6, or it is not drawn at all
    public static final int MUTED = 0xFF8B95A1;
    public static final int ACCENT = 0xFF3FD3FF;
    private final Identifier tex;
    protected @Nullable IntervalBox interval;

    protected DarkScreen(M menu, Inventory inv, Component title, String texture, int w, int h) {
        super(menu, inv, title, w, h);
        this.tex = Identifier.fromNamespaceAndPath(OmniLogistics.MODID, "textures/gui/" + texture + ".png");
        titleLabelX = 8;
        titleLabelY = 6;
        inventoryLabelX = 8;
        inventoryLabelY = h - 94;
    }

    /** The machine clock: a free {@link IntervalHost#MIN}..{@link IntervalHost#MAX} tick field, no upgrade in the way. */
    protected void addIntervalBox(int x, int y, int w, BlockPos pos, IntSupplier value) {
        interval = addRenderableWidget(new IntervalBox(font, leftPos + x, topPos + y, w, pos, value));
    }

    @Override
    public void extractRenderState(GuiGraphicsExtractor g, int mouseX, int mouseY, float partialTick) {
        if (interval != null) interval.refresh();
        super.extractRenderState(g, mouseX, mouseY, partialTick);
    }

    /** Vanilla never blurs a widget on a click that misses it, so without this the field would keep the keyboard - and never
     *  commit - until the screen closed. */
    @Override
    public boolean mouseClicked(net.minecraft.client.input.MouseButtonEvent e, boolean doubleClick) {
        if (interval != null && interval.isFocused() && !interval.isMouseOver(e.x(), e.y())) setFocused(null);
        return super.mouseClicked(e, doubleClick);
    }

    /** While the field has the keyboard, digits must not swap hotbar slots or close the screen (the anvil does the same). */
    @Override
    public boolean keyPressed(net.minecraft.client.input.KeyEvent e) {
        if (interval != null && interval.canConsumeInput() && e.key() != InputConstants.KEY_ESCAPE) {
            interval.keyPressed(e);
            return true;
        }
        return super.keyPressed(e);
    }

    /** Closing the screen mid-edit sends the value instead of dropping it. */
    @Override
    public void removed() {
        if (interval != null) interval.setFocused(false);
        super.removed();
    }

    @Override
    public void extractBackground(GuiGraphicsExtractor g, int mouseX, int mouseY, float partialTick) {
        int sheet = Math.max(imageWidth, imageHeight) <= 256 ? 256 : 512;   // tall panels (the 16 / 64 filter) come off the bigger sheet
        g.blit(tex, leftPos, topPos, 0, 0, imageWidth, imageHeight, sheet, sheet);
    }

    @Override
    protected void extractLabels(GuiGraphicsExtractor g, int mouseX, int mouseY) {
        g.text(font, title, titleLabelX, titleLabelY, TEXT, false);
        g.text(font, playerInventoryTitle, inventoryLabelX, inventoryLabelY, MUTED, false);
    }
}
