package com.mertokan.omnilogistics.core;

import com.mertokan.omnilogistics.OmniLogistics;
import com.mojang.blaze3d.platform.InputConstants;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.client.gui.screens.inventory.AbstractContainerScreen;
import net.minecraft.core.BlockPos;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.player.Inventory;
import net.minecraft.world.inventory.AbstractContainerMenu;
import org.jetbrains.annotations.Nullable;

import java.util.function.IntSupplier;

/** Textured dark panel + light labels. Textures are generated by tools/gen_textures.py (256x256, or 512x512 when the panel is taller). */
public abstract class DarkScreen<M extends AbstractContainerMenu> extends AbstractContainerScreen<M> {
    public static final int TEXT = 0xE6EDF3;
    public static final int MUTED = 0x8B95A1;
    public static final int ACCENT = 0x3FD3FF;
    private final ResourceLocation tex;
    protected @Nullable IntervalBox interval;

    protected DarkScreen(M menu, Inventory inv, Component title, String texture, int w, int h) {
        super(menu, inv, title);
        this.tex = ResourceLocation.fromNamespaceAndPath(OmniLogistics.MODID, "textures/gui/" + texture + ".png");
        imageWidth = w;
        imageHeight = h;
        titleLabelX = 8;
        titleLabelY = 6;
        inventoryLabelX = 8;
        inventoryLabelY = h - 94;
    }

    /** The machine clock: a free {@link IntervalHost#MIN}..{@link IntervalHost#MAX} tick field, no upgrade in the way. */
    protected void addIntervalBox(int x, int y, int w, BlockPos pos, IntSupplier value) {
        interval = addRenderableWidget(new IntervalBox(font, leftPos + x, topPos + y, w, pos, value));
    }

    @Override
    public void render(GuiGraphics g, int mouseX, int mouseY, float partialTick) {
        if (interval != null) interval.refresh();
        super.render(g, mouseX, mouseY, partialTick);
        renderTooltip(g, mouseX, mouseY);
    }

    /** Vanilla never blurs a widget on a click that misses it, so without this the field would keep the keyboard - and never
     *  commit - until the screen closed. */
    @Override
    public boolean mouseClicked(double mx, double my, int button) {
        if (interval != null && interval.isFocused() && !interval.isMouseOver(mx, my)) setFocused(null);
        return super.mouseClicked(mx, my, button);
    }

    /** While the field has the keyboard, digits must not swap hotbar slots or close the screen (the anvil does the same). */
    @Override
    public boolean keyPressed(int key, int scan, int mods) {
        if (interval != null && interval.canConsumeInput() && key != InputConstants.KEY_ESCAPE) {
            interval.keyPressed(key, scan, mods);
            return true;
        }
        return super.keyPressed(key, scan, mods);
    }

    /** Closing the screen mid-edit sends the value instead of dropping it. */
    @Override
    public void removed() {
        if (interval != null) interval.setFocused(false);
        super.removed();
    }

    @Override
    protected void renderBg(GuiGraphics g, float partialTick, int mouseX, int mouseY) {
        int sheet = Math.max(imageWidth, imageHeight) <= 256 ? 256 : 512;   // tall panels (the 16 / 64 filter) come off the bigger sheet
        g.blit(tex, leftPos, topPos, 0, 0, imageWidth, imageHeight, sheet, sheet);
    }

    @Override
    protected void renderLabels(GuiGraphics g, int mouseX, int mouseY) {
        g.drawString(font, title, titleLabelX, titleLabelY, TEXT, false);
        g.drawString(font, playerInventoryTitle, inventoryLabelX, inventoryLabelY, MUTED, false);
    }
}
